spring:
  datasource:
    url: jdbc:mysql://${testDbIp:127.0.0.1}:3306/payments_exam_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${testDbId:root}
    password: ${testDbPw:}
  jpa:
    hibernate:
      ddl-auto: create